namespace FamilyHub.Modules.Auth.Domain.ValueObjects;

/// <summary>
/// Represents a hashed password using Argon2id algorithm.
/// The hash is generated by IPasswordService and should never be validated here
/// (the hash itself is always valid once generated).
/// </summary>
[ValueObject<string>(conversions: Conversions.Default | Conversions.EfCoreValueConverter)]
public readonly partial struct PasswordHash
{
    // No validation needed - the hash is generated internally by PasswordService
    // and will always be in a valid format. We trust the hashing algorithm.

    /// <summary>
    /// Creates a PasswordHash from a pre-computed hash string.
    /// This should only be called with output from IPasswordService.HashPassword().
    /// </summary>
    public static PasswordHash FromHash(string hash) => From(hash);
}
