// <auto-generated />
using System;
using FamilyHub.Api.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213104514_RemoveCalendarEventType")]
    partial class RemoveCalendarEventType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyHub.Api.Features.Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("KEYCLOAK")
                        .HasColumnName("external_provider");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_user_id");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_user_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_users_family_id");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasIndex("CreatedBy", "StartTime")
                        .HasDatabaseName("ix_calendar_events_created_by_start_time");

                    b.HasIndex("FamilyId", "StartTime")
                        .HasDatabaseName("ix_calendar_events_family_id_start_time");

                    b.ToTable("calendar_events", "calendar");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEventAttendee", b =>
                {
                    b.Property<Guid>("CalendarEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CalendarEventId", "UserId")
                        .HasName("pk_calendar_event_attendees");

                    b.ToTable("calendar_event_attendees", "calendar");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_families_owner_id");

                    b.ToTable("families", "family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invitee_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_family_invitations");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_family_invitations_accepted_by_user_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_family_invitations_invited_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_family_invitations_token_hash");

                    b.HasIndex("FamilyId", "Status")
                        .HasDatabaseName("ix_family_invitations_family_id_status");

                    b.ToTable("family_invitations", "family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.HasIndex("FamilyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_user_id");

                    b.ToTable("family_members", "family");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_name");

                    b.Property<string>("TriggerDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_description");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_event_type");

                    b.Property<string>("TriggerModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_module");

                    b.Property<string>("TriggerOutputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_output_schema");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_chain_definitions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_chain_definitions_family_id");

                    b.HasIndex("TemplateName")
                        .HasDatabaseName("ix_chain_definitions_template_name")
                        .HasFilter("is_template = true");

                    b.HasIndex("TriggerEventType")
                        .HasDatabaseName("ix_chain_definitions_trigger_event_type")
                        .HasFilter("is_enabled = true");

                    b.ToTable("chain_definitions", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinitionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActionVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_version");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<Guid>("ChainDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_definition_id");

                    b.Property<string>("CompensationActionType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("compensation_action_type");

                    b.Property<string>("ConditionExpression")
                        .HasColumnType("text")
                        .HasColumnName("condition_expression");

                    b.Property<string>("InputMappings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("input_mappings");

                    b.Property<bool>("IsCompensatable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_compensatable");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_chain_definition_steps");

                    b.HasIndex("ChainDefinitionId")
                        .HasDatabaseName("ix_chain_definition_steps_definition_id");

                    b.HasIndex("ChainDefinitionId", "Alias")
                        .IsUnique()
                        .HasDatabaseName("uq_chain_step_alias");

                    b.HasIndex("ChainDefinitionId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_chain_step_order");

                    b.ToTable("chain_definition_steps", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainEntityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChainExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_execution_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("StepAlias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_alias");

                    b.HasKey("Id")
                        .HasName("pk_chain_entity_mappings");

                    b.HasIndex("ChainExecutionId")
                        .HasDatabaseName("ix_chain_entity_mappings_execution_id");

                    b.HasIndex("EntityId", "EntityType")
                        .HasDatabaseName("ix_chain_entity_mappings_entity");

                    b.HasIndex("Module", "EntityType")
                        .HasDatabaseName("ix_chain_entity_mappings_module");

                    b.ToTable("chain_entity_mappings", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChainDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_definition_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("context");

                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CurrentStepIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step_index");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TriggerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_event_id");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_event_type");

                    b.Property<string>("TriggerPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_payload");

                    b.HasKey("Id")
                        .HasName("pk_chain_executions");

                    b.HasIndex("ChainDefinitionId")
                        .HasDatabaseName("ix_chain_executions_definition_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_chain_executions_correlation_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_chain_executions_family_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_chain_executions_status")
                        .HasFilter("status IN ('Pending', 'Running', 'Compensating')");

                    b.ToTable("chain_executions", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainScheduledJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChainExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_execution_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("StepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_chain_scheduled_jobs");

                    b.HasIndex("ChainExecutionId")
                        .HasDatabaseName("ix_chain_scheduled_jobs_chain_execution_id");

                    b.HasIndex("PickedUpAt")
                        .HasDatabaseName("ix_chain_scheduled_jobs_stale")
                        .HasFilter("completed_at IS NULL AND failed_at IS NULL AND picked_up_at IS NOT NULL");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_chain_scheduled_jobs_ready")
                        .HasFilter("picked_up_at IS NULL AND completed_at IS NULL AND failed_at IS NULL");

                    b.HasIndex("StepExecutionId")
                        .HasDatabaseName("ix_chain_scheduled_jobs_step_execution_id");

                    b.ToTable("chain_scheduled_jobs", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.StepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ChainExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_execution_id");

                    b.Property<DateTime?>("CompensatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compensated_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_retries");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_payload");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("StepAlias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_alias");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("step_name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_step_executions");

                    b.HasIndex("ChainExecutionId")
                        .HasDatabaseName("ix_step_executions_chain_execution_id");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_step_executions_scheduled")
                        .HasFilter("status = 'Pending' AND scheduled_at IS NOT NULL AND picked_up_at IS NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_step_executions_status")
                        .HasFilter("status IN ('Pending', 'Running')");

                    b.HasIndex("ChainExecutionId", "StepAlias")
                        .IsUnique()
                        .HasDatabaseName("uq_step_execution_alias");

                    b.ToTable("step_executions", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Auth.Domain.Entities.User", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Family.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEventAttendee", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEvent", "CalendarEvent")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_event_attendees_calendar_events_calendar_event_id");

                    b.Navigation("CalendarEvent");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.Family", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_families_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyInvitation", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_family_invitations_users_accepted_by_user_id");

                    b.HasOne("FamilyHub.Api.Features.Family.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_invitations_families_family_id");

                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_invitations_users_invited_by_user_id");

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Family");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Family.Domain.Entities.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinitionStep", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainDefinition", null)
                        .WithMany("Steps")
                        .HasForeignKey("ChainDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_definition_steps_chain_definitions_chain_definition_id");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainExecution", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainDefinition", "ChainDefinition")
                        .WithMany()
                        .HasForeignKey("ChainDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chain_executions_chain_definitions_chain_definition_id");

                    b.Navigation("ChainDefinition");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainScheduledJob", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainExecution", "ChainExecution")
                        .WithMany()
                        .HasForeignKey("ChainExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_scheduled_jobs_chain_executions_chain_execution_id");

                    b.HasOne("FamilyHub.EventChain.Domain.Entities.StepExecution", "StepExecution")
                        .WithMany()
                        .HasForeignKey("StepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_scheduled_jobs_step_executions_step_execution_id");

                    b.Navigation("ChainExecution");

                    b.Navigation("StepExecution");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.StepExecution", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainExecution", null)
                        .WithMany("StepExecutions")
                        .HasForeignKey("ChainExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_executions_chain_executions_chain_execution_id");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEvent", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.Family", b =>
                {
                    b.Navigation("FamilyMembers");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinition", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainExecution", b =>
                {
                    b.Navigation("StepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
