// <auto-generated />
using System;
using FamilyHub.Api.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224072504_AddFileManagementEntities")]
    partial class AddFileManagementEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyHub.Api.Common.Infrastructure.Avatar.AvatarAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OriginalMimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("original_mime_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_avatars");

                    b.ToTable("avatars", "avatar");
                });

            modelBuilder.Entity("FamilyHub.Api.Common.Infrastructure.Avatar.AvatarVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_avatar_variants");

                    b.HasIndex("AvatarId", "Size")
                        .IsUnique()
                        .HasDatabaseName("ix_avatar_variants_avatar_id_size");

                    b.ToTable("avatar_variants", "avatar");
                });

            modelBuilder.Entity("FamilyHub.Api.Common.Infrastructure.Avatar.StoredFile", b =>
                {
                    b.Property<string>("StorageKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.HasKey("StorageKey")
                        .HasName("pk_stored_files");

                    b.ToTable("stored_files", "storage");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("KEYCLOAK")
                        .HasColumnName("external_provider");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_user_id");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("preferred_locale");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_user_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_users_family_id");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasIndex("CreatedBy", "StartTime")
                        .HasDatabaseName("ix_calendar_events_created_by_start_time");

                    b.HasIndex("FamilyId", "StartTime")
                        .HasDatabaseName("ix_calendar_events_family_id_start_time");

                    b.ToTable("calendar_events", "calendar");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEventAttendee", b =>
                {
                    b.Property<Guid>("CalendarEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CalendarEventId", "UserId")
                        .HasName("pk_calendar_event_attendees");

                    b.ToTable("calendar_event_attendees", "calendar");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Dashboard.Domain.Entities.DashboardLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_layouts");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_dashboard_layouts_family_id")
                        .HasFilter("\"family_id\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dashboard_layouts_user_id")
                        .HasFilter("\"user_id\" IS NOT NULL");

                    b.ToTable("dashboard_layouts", "dashboard");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Dashboard.Domain.Entities.DashboardWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WidgetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("widget_type");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_widgets");

                    b.HasIndex("DashboardId")
                        .HasDatabaseName("ix_dashboard_widgets_dashboard_id");

                    b.ToTable("dashboard_widgets", "dashboard");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_families_owner_id");

                    b.ToTable("families", "family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invitee_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_family_invitations");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_family_invitations_accepted_by_user_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_family_invitations_invited_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_family_invitations_token_hash");

                    b.HasIndex("FamilyId", "Status")
                        .HasDatabaseName("ix_family_invitations_family_id_status");

                    b.ToTable("family_invitations", "family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.HasIndex("FamilyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_user_id");

                    b.ToTable("family_members", "family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CoverFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_file_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_albums_family_id");

                    b.ToTable("albums", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.AlbumItem", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.HasKey("AlbumId", "FileId")
                        .HasName("pk_album_items");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_album_items_album_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_album_items_file_id");

                    b.ToTable("album_items", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.ExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<Guid>("ConnectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_access_token");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_refresh_token");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_external_connections");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_external_connections_family_id");

                    b.HasIndex("FamilyId", "ProviderType")
                        .IsUnique()
                        .HasDatabaseName("ix_external_connections_family_id_provider_type");

                    b.ToTable("external_connections", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("camera_model");

                    b.Property<DateTime?>("CaptureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_date");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("gps_latitude");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("gps_longitude");

                    b.Property<string>("LocationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_name");

                    b.Property<string>("RawExif")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_exif");

                    b.HasKey("FileId")
                        .HasName("pk_file_metadata");

                    b.ToTable("file_metadata", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.FilePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.HasKey("Id")
                        .HasName("pk_file_permissions");

                    b.HasIndex("MemberId", "FamilyId")
                        .HasDatabaseName("ix_file_permissions_member_id_family_id");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_file_permissions_resource_type_resource_id");

                    b.HasIndex("MemberId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_permissions_member_id_resource_type_resource_id");

                    b.ToTable("file_permissions", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.FileTag", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("FileId", "TagId")
                        .HasName("pk_file_tags");

                    b.ToTable("file_tags", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.FileThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_file_thumbnails");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_thumbnails_file_id");

                    b.HasIndex("FileId", "Width", "Height")
                        .IsUnique()
                        .HasDatabaseName("ix_file_thumbnails_file_id_width_height");

                    b.ToTable("file_thumbnails", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_file_versions");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_versions_file_id");

                    b.HasIndex("FileId", "IsCurrent")
                        .HasDatabaseName("ix_file_versions_file_id_is_current");

                    b.ToTable("file_versions", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsInbox")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_inbox");

                    b.Property<string>("MaterializedPath")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("materialized_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_folder_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_folders_family_id");

                    b.HasIndex("MaterializedPath")
                        .HasDatabaseName("ix_folders_materialized_path");

                    b.HasIndex("ParentFolderId")
                        .HasDatabaseName("ix_folders_parent_folder_id");

                    b.HasIndex("FamilyId", "IsInbox")
                        .HasDatabaseName("ix_folders_family_id_is_inbox");

                    b.ToTable("folders", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.OrganizationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actions_json");

                    b.Property<int>("ConditionLogic")
                        .HasColumnType("integer")
                        .HasColumnName("condition_logic");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organization_rules");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_organization_rules_family_id");

                    b.HasIndex("FamilyId", "Priority")
                        .HasDatabaseName("ix_organization_rules_family_id_priority");

                    b.ToTable("organization_rules", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.ProcessingLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActionTaken")
                        .HasColumnType("integer")
                        .HasColumnName("action_taken");

                    b.Property<string>("AppliedTagNames")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("applied_tag_names");

                    b.Property<Guid?>("DestinationFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_folder_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("MatchedRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_rule_id");

                    b.Property<string>("MatchedRuleName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("matched_rule_name");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_processing_log");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_processing_log_family_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processing_log_processed_at");

                    b.ToTable("processing_log", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.RecentSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("query");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recent_searches");

                    b.HasIndex("UserId", "SearchedAt")
                        .HasDatabaseName("ix_recent_searches_user_id_searched_at");

                    b.ToTable("recent_searches", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FiltersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("filters_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("query");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_searches");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_searches_user_id");

                    b.ToTable("saved_searches", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.SecureNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_content");

                    b.Property<string>("EncryptedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_title");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("iv");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("salt");

                    b.Property<string>("Sentinel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentinel");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_secure_notes");

                    b.HasIndex("UserId", "FamilyId")
                        .HasDatabaseName("ix_secure_notes_user_id_family_id");

                    b.HasIndex("UserId", "FamilyId", "Category")
                        .HasDatabaseName("ix_secure_notes_user_id_family_id_category");

                    b.ToTable("secure_notes", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("integer")
                        .HasColumnName("max_downloads");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_share_links");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_share_links_family_id");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_share_links_resource_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_share_links_token");

                    b.ToTable("share_links", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.ShareLinkAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("ShareLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_link_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_share_link_access_log");

                    b.HasIndex("ShareLinkId")
                        .HasDatabaseName("ix_share_link_access_log_share_link_id");

                    b.ToTable("share_link_access_log", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_files_family_id");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_files_folder_id");

                    b.ToTable("files", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("FamilyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_family_id_name");

                    b.ToTable("tags", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTime>("FavoritedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("favorited_at");

                    b.HasKey("UserId", "FileId")
                        .HasName("pk_user_favorites");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_user_favorites_file_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_favorites_user_id");

                    b.ToTable("user_favorites", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Domain.Entities.ZipJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.PrimitiveCollection<string>("FileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("file_ids");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<long?>("ZipSize")
                        .HasColumnType("bigint")
                        .HasColumnName("zip_size");

                    b.Property<string>("ZipStorageKey")
                        .HasColumnType("text")
                        .HasColumnName("zip_storage_key");

                    b.HasKey("Id")
                        .HasName("pk_zip_jobs");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_zip_jobs_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_zip_jobs_family_id");

                    b.ToTable("zip_jobs", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Infrastructure.Data.FileBlob", b =>
                {
                    b.Property<string>("StorageKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("StorageKey")
                        .HasName("pk_file_blobs");

                    b.ToTable("file_blobs", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Infrastructure.Data.StorageQuota", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<long>("MaxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("UsedBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("used_bytes");

                    b.HasKey("FamilyId")
                        .HasName("pk_storage_quotas");

                    b.ToTable("storage_quotas", "file_management");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.FileManagement.Infrastructure.Data.UploadChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("upload_id");

                    b.HasKey("Id")
                        .HasName("pk_upload_chunks");

                    b.HasIndex("UploadId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_upload_chunks_upload_id_chunk_index");

                    b.ToTable("upload_chunks", "file_management");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_name");

                    b.Property<string>("TriggerDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_description");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_event_type");

                    b.Property<string>("TriggerModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_module");

                    b.Property<string>("TriggerOutputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_output_schema");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_chain_definitions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_chain_definitions_family_id");

                    b.HasIndex("TemplateName")
                        .HasDatabaseName("ix_chain_definitions_template_name")
                        .HasFilter("is_template = true");

                    b.HasIndex("TriggerEventType")
                        .HasDatabaseName("ix_chain_definitions_trigger_event_type")
                        .HasFilter("is_enabled = true");

                    b.ToTable("chain_definitions", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinitionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActionVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_version");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<Guid>("ChainDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_definition_id");

                    b.Property<string>("CompensationActionType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("compensation_action_type");

                    b.Property<string>("ConditionExpression")
                        .HasColumnType("text")
                        .HasColumnName("condition_expression");

                    b.Property<string>("InputMappings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("input_mappings");

                    b.Property<bool>("IsCompensatable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_compensatable");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_chain_definition_steps");

                    b.HasIndex("ChainDefinitionId")
                        .HasDatabaseName("ix_chain_definition_steps_definition_id");

                    b.HasIndex("ChainDefinitionId", "Alias")
                        .IsUnique()
                        .HasDatabaseName("uq_chain_step_alias");

                    b.HasIndex("ChainDefinitionId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_chain_step_order");

                    b.ToTable("chain_definition_steps", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainEntityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChainExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_execution_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("StepAlias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_alias");

                    b.HasKey("Id")
                        .HasName("pk_chain_entity_mappings");

                    b.HasIndex("ChainExecutionId")
                        .HasDatabaseName("ix_chain_entity_mappings_execution_id");

                    b.HasIndex("EntityId", "EntityType")
                        .HasDatabaseName("ix_chain_entity_mappings_entity");

                    b.HasIndex("Module", "EntityType")
                        .HasDatabaseName("ix_chain_entity_mappings_module");

                    b.ToTable("chain_entity_mappings", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChainDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_definition_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("context");

                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CurrentStepIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step_index");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TriggerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_event_id");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_event_type");

                    b.Property<string>("TriggerPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_payload");

                    b.HasKey("Id")
                        .HasName("pk_chain_executions");

                    b.HasIndex("ChainDefinitionId")
                        .HasDatabaseName("ix_chain_executions_definition_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_chain_executions_correlation_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_chain_executions_family_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_chain_executions_status")
                        .HasFilter("status IN ('Pending', 'Running', 'Compensating')");

                    b.ToTable("chain_executions", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainScheduledJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChainExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_execution_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("StepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_chain_scheduled_jobs");

                    b.HasIndex("ChainExecutionId")
                        .HasDatabaseName("ix_chain_scheduled_jobs_chain_execution_id");

                    b.HasIndex("PickedUpAt")
                        .HasDatabaseName("ix_chain_scheduled_jobs_stale")
                        .HasFilter("completed_at IS NULL AND failed_at IS NULL AND picked_up_at IS NOT NULL");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_chain_scheduled_jobs_ready")
                        .HasFilter("picked_up_at IS NULL AND completed_at IS NULL AND failed_at IS NULL");

                    b.HasIndex("StepExecutionId")
                        .HasDatabaseName("ix_chain_scheduled_jobs_step_execution_id");

                    b.ToTable("chain_scheduled_jobs", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.StepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ChainExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_execution_id");

                    b.Property<DateTime?>("CompensatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compensated_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_retries");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_payload");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("StepAlias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_alias");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("step_name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_step_executions");

                    b.HasIndex("ChainExecutionId")
                        .HasDatabaseName("ix_step_executions_chain_execution_id");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_step_executions_scheduled")
                        .HasFilter("status = 'Pending' AND scheduled_at IS NOT NULL AND picked_up_at IS NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_step_executions_status")
                        .HasFilter("status IN ('Pending', 'Running')");

                    b.HasIndex("ChainExecutionId", "StepAlias")
                        .IsUnique()
                        .HasDatabaseName("uq_step_execution_alias");

                    b.ToTable("step_executions", "event_chain");
                });

            modelBuilder.Entity("FamilyHub.Api.Common.Infrastructure.Avatar.AvatarVariant", b =>
                {
                    b.HasOne("FamilyHub.Api.Common.Infrastructure.Avatar.AvatarAggregate", "Avatar")
                        .WithMany("Variants")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avatar_variants_avatars_avatar_id");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Auth.Domain.Entities.User", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Family.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEventAttendee", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEvent", "CalendarEvent")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_event_attendees_calendar_events_calendar_event_id");

                    b.Navigation("CalendarEvent");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Dashboard.Domain.Entities.DashboardWidget", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Dashboard.Domain.Entities.DashboardLayout", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_widgets_dashboard_layouts_dashboard_id");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.Family", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_families_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyInvitation", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_family_invitations_users_accepted_by_user_id");

                    b.HasOne("FamilyHub.Api.Features.Family.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_invitations_families_family_id");

                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_invitations_users_invited_by_user_id");

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Family");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("FamilyHub.Api.Features.Family.Domain.Entities.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.HasOne("FamilyHub.Api.Features.Auth.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinitionStep", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainDefinition", null)
                        .WithMany("Steps")
                        .HasForeignKey("ChainDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_definition_steps_chain_definitions_chain_definition_id");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainExecution", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainDefinition", "ChainDefinition")
                        .WithMany()
                        .HasForeignKey("ChainDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chain_executions_chain_definitions_chain_definition_id");

                    b.Navigation("ChainDefinition");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainScheduledJob", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainExecution", "ChainExecution")
                        .WithMany()
                        .HasForeignKey("ChainExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_scheduled_jobs_chain_executions_chain_execution_id");

                    b.HasOne("FamilyHub.EventChain.Domain.Entities.StepExecution", "StepExecution")
                        .WithMany()
                        .HasForeignKey("StepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_scheduled_jobs_step_executions_step_execution_id");

                    b.Navigation("ChainExecution");

                    b.Navigation("StepExecution");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.StepExecution", b =>
                {
                    b.HasOne("FamilyHub.EventChain.Domain.Entities.ChainExecution", null)
                        .WithMany("StepExecutions")
                        .HasForeignKey("ChainExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_executions_chain_executions_chain_execution_id");
                });

            modelBuilder.Entity("FamilyHub.Api.Common.Infrastructure.Avatar.AvatarAggregate", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Calendar.Domain.Entities.CalendarEvent", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Dashboard.Domain.Entities.DashboardLayout", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("FamilyHub.Api.Features.Family.Domain.Entities.Family", b =>
                {
                    b.Navigation("FamilyMembers");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainDefinition", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FamilyHub.EventChain.Domain.Entities.ChainExecution", b =>
                {
                    b.Navigation("StepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
