// <auto-generated />
using FamilyHub.Api.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FamilyHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202120000_AddRlsPolicies")]
    partial class AddRlsPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only adds RLS policies via SQL, no model changes
            // Model remains the same as previous migration (InitialCreate)
            // Designer file required for EF Core migration tracking
        }
    }
}
