# Family Hub — Multi-Environment CLI
# Requires: https://taskfile.dev (v3+)
#
# Quick start:
#   task setup:certs      # one-time: generate TLS certificates
#   task shared:up        # start shared services (Keycloak, MailHog, Traefik, proxies)
#   task up               # provision realm + start per-env services
#   task down             # stop per-env (data persists)
#   task env:destroy      # stop + remove volumes + delete realm

version: '3'

vars:
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  ENV_NAME:
    sh: echo "{{.BRANCH}}" | tr '/_' '-' | tr '[:upper:]' '[:lower:]' | sed 's/^-//;s/-$//'
  DOCKER_UID:
    sh: id -u
  DOCKER_GID:
    sh: id -g
  SRC_ROOT:
    sh: echo "$(git rev-parse --show-toplevel)/src"
  INFRA_DIR: ./infrastructure
  TRAEFIK_COMPOSE: '{{.INFRA_DIR}}/docker-compose.traefik.yml'
  SHARED_COMPOSE: '{{.INFRA_DIR}}/docker-compose.shared.yml'
  ENV_COMPOSE: '{{.INFRA_DIR}}/docker-compose.env.yml'
  # Explicit project names prevent orphan-container warnings between compose files
  DC_TRAEFIK: 'docker compose -p fh-traefik -f {{.INFRA_DIR}}/docker-compose.traefik.yml'
  DC_SHARED: 'docker compose -p fh-shared -f {{.INFRA_DIR}}/docker-compose.shared.yml'

tasks:
  # ---------------------------------------------------------------------------
  # Setup
  # ---------------------------------------------------------------------------
  setup:certs:
    desc: Generate mkcert TLS certificates (idempotent)
    cmds:
      - bash {{.INFRA_DIR}}/scripts/setup-certs.sh
    status:
      - test -f {{.INFRA_DIR}}/certs/local.pem

  setup:hooks:
    desc: Configure git to use .githooks directory (idempotent)
    cmds:
      - git config core.hooksPath .githooks
    status:
      - test "$(git config core.hooksPath)" = ".githooks"

  setup:network:
    desc: Create traefik-public Docker network (idempotent)
    cmds:
      - docker network create traefik-public 2>/dev/null || true
    status:
      - docker network inspect traefik-public >/dev/null 2>&1

  setup:proxy-volumes:
    desc: Create external Docker volumes for package caching proxies (idempotent)
    cmds:
      - docker volume create fh-proxy-verdaccio
      - docker volume create fh-proxy-baget
      - docker volume create fh-proxy-registry-dockerhub
      - docker volume create fh-proxy-registry-mcr
      - docker volume create fh-proxy-registry-ghcr
      - docker volume create fh-infisical-pg
      - docker volume create fh-infisical-redis
    status:
      - docker volume inspect fh-proxy-verdaccio >/dev/null 2>&1
      - docker volume inspect fh-proxy-baget >/dev/null 2>&1
      - docker volume inspect fh-proxy-registry-dockerhub >/dev/null 2>&1
      - docker volume inspect fh-proxy-registry-mcr >/dev/null 2>&1
      - docker volume inspect fh-proxy-registry-ghcr >/dev/null 2>&1
      - docker volume inspect fh-infisical-pg >/dev/null 2>&1
      - docker volume inspect fh-infisical-redis >/dev/null 2>&1

  # ---------------------------------------------------------------------------
  # Shared layer (Traefik + Keycloak + MailHog + Infisical + proxies)
  # ---------------------------------------------------------------------------
  shared:up:
    desc: Start all shared services (Traefik, Keycloak, MailHog, Infisical, proxies)
    deps: [setup:certs, setup:network, setup:proxy-volumes]
    cmds:
      - '{{.DC_TRAEFIK}} up -d'
      - '{{.DC_SHARED}} up -d'
      - echo ""
      - echo "  Shared services starting..."
      - echo "  Keycloak may take 30-60s on first start."
      - echo "  Check status with 'task shared:status'"
      - echo ""

  shared:down:
    desc: Stop shared services
    cmds:
      - '{{.DC_SHARED}} down'
      - '{{.DC_TRAEFIK}} down'

  shared:status:
    desc: Health check shared services
    cmds:
      - bash {{.INFRA_DIR}}/scripts/health-check.sh shared

  shared:logs:
    desc: Follow shared service logs
    cmds:
      - '{{.DC_TRAEFIK}} logs -f {{.CLI_ARGS}}'

  # ---------------------------------------------------------------------------
  # Per-environment lifecycle
  # ---------------------------------------------------------------------------
  env:up:
    desc: 'Provision realm + start environment for current branch ({{.ENV_NAME}})'
    deps: [shared:up, setup:hooks]
    cmds:
      # Provision Keycloak realm for this environment
      - bash {{.INFRA_DIR}}/keycloak/provision-realm.sh "{{.ENV_NAME}}"
      # Fetch Infisical secrets (if configured)
      - |
        SECRETS=$(bash {{.INFRA_DIR}}/scripts/fetch-infisical-secrets.sh 2>/dev/null) && eval "$SECRETS"
        ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} up -d --build
      # Show URLs
      - task: urls
    env:
      ENV_NAME: '{{.ENV_NAME}}'
      DOCKER_UID: '{{.DOCKER_UID}}'
      DOCKER_GID: '{{.DOCKER_GID}}'
      SRC_ROOT: '{{.SRC_ROOT}}'

  env:secrets:
    desc: 'Show secrets that would be fetched from Infisical (debug)'
    cmds:
      - bash {{.INFRA_DIR}}/scripts/fetch-infisical-secrets.sh

  env:down:
    desc: 'Stop environment (data persists)'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} down

  env:destroy:
    desc: 'Stop environment + remove volumes + delete realm (clean slate)'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} down -v
      - bash {{.INFRA_DIR}}/keycloak/provision-realm.sh "{{.ENV_NAME}}" --delete

  env:logs:
    desc: 'Follow environment logs (optional: task env:logs -- api)'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} logs -f {{.CLI_ARGS}}

  env:ps:
    desc: 'Show running containers for current environment'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} ps

  env:name:
    desc: 'Print environment name for current branch'
    cmds:
      - echo "{{.ENV_NAME}}"

  # ---------------------------------------------------------------------------
  # Quick aliases
  # ---------------------------------------------------------------------------
  up:
    desc: 'Alias for env:up — start environment for current branch'
    cmds:
      - task: env:up

  down:
    desc: 'Alias for env:down — stop environment'
    cmds:
      - task: env:down

  # ---------------------------------------------------------------------------
  # Status & information
  # ---------------------------------------------------------------------------
  status:
    desc: 'Full health dashboard (shared + environment)'
    cmds:
      - bash {{.INFRA_DIR}}/scripts/health-check.sh all "{{.ENV_NAME}}"

  urls:
    desc: 'Show URLs for current environment'
    cmds:
      - |
        echo ""
        echo "  Environment: {{.ENV_NAME}}"
        echo "  ──────────────────────────────────────────"
        echo "  App:         https://{{.ENV_NAME}}.localhost:4443"
        echo "  API:         https://api-{{.ENV_NAME}}.localhost:4443/graphql"
        echo "  pgAdmin:     https://pgadmin-{{.ENV_NAME}}.localhost:4443"
        echo "  ──────────────────────────────────────────"
        echo "  Shared services:"
        echo "  Keycloak:    https://auth.localhost:4443"
        echo "  MailHog:     https://mail.localhost:4443"
        echo "  Infisical:   https://secrets.localhost:4443  (localhost:8180)"
        echo "  Hub:         https://hub.localhost:4443"
        echo "  Traefik:     http://localhost:8888"
        echo "  ──────────────────────────────────────────"
        echo "  Proxies:"
        echo "  npm:         https://npm.localhost:4443    (localhost:4873)"
        echo "  NuGet:       https://nuget.localhost:4443  (localhost:5555)"
        echo "  DockerHub:   localhost:5001"
        echo "  MCR:         localhost:5002"
        echo "  GHCR:        localhost:5003"
        echo "  ──────────────────────────────────────────"
        echo "  Keycloak realm: FamilyHub-{{.ENV_NAME}}"
        echo ""

  list:
    desc: 'List all running FamilyHub environments'
    cmds:
      - |
        echo ""
        echo "  Running FamilyHub environments:"
        echo "  ──────────────────────────────────────────"
        docker ps --filter "label=com.docker.compose.project" --format "{{`{{.Names}}`}}\t{{`{{.Status}}`}}" | grep "^fh-" | awk -F'[-_]' '{env=$2; for(i=3;i<NF;i++) env=env"-"$i; print env}' | sort -u | while read env; do
          echo "  - $env"
        done 2>/dev/null || echo "  No environments running."
        echo ""

  # ---------------------------------------------------------------------------
  # Package caching proxies
  # ---------------------------------------------------------------------------
  proxy:status:
    desc: 'Show proxy container status and volume sizes'
    cmds:
      - |
        echo ""
        echo "  Proxy Containers:"
        echo "  ──────────────────────────────────────────"
        {{.DC_TRAEFIK}} ps --format "table {{`{{.Name}}`}}\t{{`{{.Status}}`}}\t{{`{{.Ports}}`}}" | grep -E "(verdaccio|baget|registry)" || echo "  No proxy containers running."
        echo ""

  proxy:logs:
    desc: 'Follow proxy service logs'
    cmds:
      - '{{.DC_TRAEFIK}} logs -f verdaccio baget registry-dockerhub registry-mcr registry-ghcr {{.CLI_ARGS}}'

  proxy:usage:
    desc: 'Show cache disk usage'
    cmds:
      - |
        echo ""
        echo "  Proxy Cache Disk Usage:"
        echo "  ──────────────────────────────────────────"
        for vol in fh-proxy-verdaccio fh-proxy-baget fh-proxy-registry-dockerhub fh-proxy-registry-mcr fh-proxy-registry-ghcr; do
          size=$(docker run --rm -v "${vol}:/data" alpine sh -c "du -sh /data 2>/dev/null | cut -f1" 2>/dev/null || echo "N/A")
          printf "  %-35s %s\n" "$vol" "$size"
        done
        echo ""

  proxy:clean:
    desc: 'Stop proxies and remove cache volumes (with confirmation)'
    prompt: This will remove all cached packages (npm, NuGet, Docker images). Continue?
    cmds:
      - '{{.DC_TRAEFIK}} stop verdaccio baget registry-dockerhub registry-mcr registry-ghcr'
      - docker volume rm fh-proxy-verdaccio fh-proxy-baget fh-proxy-registry-dockerhub fh-proxy-registry-mcr fh-proxy-registry-ghcr 2>/dev/null || true
      - echo "Proxy caches removed. Run 'task shared:up' to recreate."

  # ---------------------------------------------------------------------------
  # Worktree management
  # ---------------------------------------------------------------------------
  worktree:create:
    desc: 'Create a new worktree (usage: task worktree:create -- <type> <issue> <desc>)'
    cmds:
      - bash scripts/create-worktree.sh {{.CLI_ARGS}}

  worktree:list:
    desc: 'List all git worktrees'
    cmds:
      - |
        echo ""
        echo "  Git Worktrees:"
        echo "  ──────────────────────────────────────────"
        git worktree list --porcelain | awk '
          /^worktree / { path=$2 }
          /^branch /   { branch=$2; sub("refs/heads/", "", branch) }
          /^HEAD /     { head=$2 }
          /^$/         { printf "  %-50s %s\n", path, branch; path=""; branch=""; head="" }
          END          { if (path) printf "  %-50s %s\n", path, branch }
        '
        echo ""

  hub:
    desc: 'Open Environment Hub in browser'
    cmds:
      - xdg-open https://hub.dev.andrekirst.de:4443 2>/dev/null || open https://hub.dev.andrekirst.de:4443 2>/dev/null || echo "Open https://hub.dev.andrekirst.de:4443 in your browser"
