# Family Hub — Multi-Environment CLI
# Requires: https://taskfile.dev (v3+)
#
# Quick start:
#   task setup:certs   # one-time: generate TLS certificates
#   task up            # start environment for current branch
#   task down          # stop environment (data persists)
#   task env:destroy   # stop + remove volumes (clean slate)

version: '3'

vars:
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  ENV_NAME:
    sh: echo "{{.BRANCH}}" | tr '/_' '-' | tr '[:upper:]' '[:lower:]' | sed 's/^-//;s/-$//'
  DOCKER_UID:
    sh: id -u
  DOCKER_GID:
    sh: id -g
  INFRA_DIR: ./infrastructure
  TRAEFIK_COMPOSE: '{{.INFRA_DIR}}/docker-compose.traefik.yml'
  ENV_COMPOSE: '{{.INFRA_DIR}}/docker-compose.env.yml'

tasks:
  # ---------------------------------------------------------------------------
  # Setup
  # ---------------------------------------------------------------------------
  setup:certs:
    desc: Generate mkcert TLS certificates (idempotent)
    cmds:
      - bash {{.INFRA_DIR}}/scripts/setup-certs.sh
    status:
      - test -f {{.INFRA_DIR}}/certs/local.pem

  setup:proxy-volumes:
    desc: Create external Docker volumes for package caching proxies (idempotent)
    cmds:
      - docker volume create fh-proxy-verdaccio
      - docker volume create fh-proxy-baget
      - docker volume create fh-proxy-registry-dockerhub
      - docker volume create fh-proxy-registry-mcr
      - docker volume create fh-proxy-registry-ghcr
    status:
      - docker volume inspect fh-proxy-verdaccio >/dev/null 2>&1
      - docker volume inspect fh-proxy-baget >/dev/null 2>&1
      - docker volume inspect fh-proxy-registry-dockerhub >/dev/null 2>&1
      - docker volume inspect fh-proxy-registry-mcr >/dev/null 2>&1
      - docker volume inspect fh-proxy-registry-ghcr >/dev/null 2>&1

  # ---------------------------------------------------------------------------
  # Traefik (shared proxy)
  # ---------------------------------------------------------------------------
  traefik:up:
    desc: Start shared Traefik reverse proxy
    deps: [setup:certs, setup:proxy-volumes]
    cmds:
      - docker compose -f {{.TRAEFIK_COMPOSE}} up -d
    status:
      - docker compose -f {{.TRAEFIK_COMPOSE}} ps --status running | grep -q traefik
      - docker compose -f {{.TRAEFIK_COMPOSE}} ps --status running | grep -q verdaccio

  traefik:down:
    desc: Stop shared Traefik reverse proxy
    cmds:
      - docker compose -f {{.TRAEFIK_COMPOSE}} down

  traefik:logs:
    desc: Follow Traefik logs
    cmds:
      - docker compose -f {{.TRAEFIK_COMPOSE}} logs -f

  # ---------------------------------------------------------------------------
  # Environment lifecycle
  # ---------------------------------------------------------------------------
  env:up:
    desc: 'Start environment for current branch ({{.ENV_NAME}})'
    deps: [traefik:up]
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} up -d --build
    env:
      ENV_NAME: '{{.ENV_NAME}}'
      DOCKER_UID: '{{.DOCKER_UID}}'
      DOCKER_GID: '{{.DOCKER_GID}}'

  env:down:
    desc: 'Stop environment (data persists)'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} down

  env:destroy:
    desc: 'Stop environment + remove volumes (clean slate)'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} down -v

  env:logs:
    desc: 'Follow environment logs (optional: task env:logs -- api)'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} logs -f {{.CLI_ARGS}}

  env:ps:
    desc: 'Show running containers for current environment'
    cmds:
      - ENV_NAME={{.ENV_NAME}} COMPOSE_PROJECT_NAME=fh-{{.ENV_NAME}} docker compose -f {{.ENV_COMPOSE}} ps

  env:name:
    desc: 'Print environment name for current branch'
    cmds:
      - echo "{{.ENV_NAME}}"

  # ---------------------------------------------------------------------------
  # List all running FamilyHub environments
  # ---------------------------------------------------------------------------
  list:
    desc: 'List all running FamilyHub environments'
    cmds:
      - docker ps --filter "label=com.docker.compose.project" --format "table {{`{{.Names}}`}}\t{{`{{.Status}}`}}\t{{`{{.Ports}}`}}" | grep "^fh-" || echo "No FamilyHub environments running."

  # ---------------------------------------------------------------------------
  # Quick aliases
  # ---------------------------------------------------------------------------
  up:
    desc: 'Alias for env:up'
    cmds:
      - task: env:up

  down:
    desc: 'Alias for env:down'
    cmds:
      - task: env:down

  urls:
    desc: 'Show URLs for current environment'
    cmds:
      - |
        echo ""
        echo "  Environment: {{.ENV_NAME}}"
        echo "  ──────────────────────────────────────────"
        echo "  App:       https://{{.ENV_NAME}}.localhost:4443"
        echo "  API:       https://api-{{.ENV_NAME}}.localhost:4443/graphql"
        echo "  Keycloak:  https://kc-{{.ENV_NAME}}.localhost:4443"
        echo "  MailHog:   https://mail-{{.ENV_NAME}}.localhost:4443"
        echo "  pgAdmin:   https://pgadmin-{{.ENV_NAME}}.localhost:4443"
        echo "  ──────────────────────────────────────────"
        echo "  Hub:       https://hub.localhost:4443"
        echo "  Traefik:   http://localhost:8888"
        echo "  ──────────────────────────────────────────"
        echo "  Proxies:"
        echo "  npm:       https://npm.localhost:4443    (localhost:4873)"
        echo "  NuGet:     https://nuget.localhost:4443  (localhost:5555)"
        echo "  DockerHub: localhost:5001"
        echo "  MCR:       localhost:5002"
        echo "  GHCR:      localhost:5003"
        echo ""

  # ---------------------------------------------------------------------------
  # Package caching proxies
  # ---------------------------------------------------------------------------
  proxy:status:
    desc: 'Show proxy container status and volume sizes'
    cmds:
      - |
        echo ""
        echo "  Proxy Containers:"
        echo "  ──────────────────────────────────────────"
        docker compose -f {{.TRAEFIK_COMPOSE}} ps --format "table {{`{{.Name}}`}}\t{{`{{.Status}}`}}\t{{`{{.Ports}}`}}" | grep -E "(verdaccio|baget|registry)" || echo "  No proxy containers running."
        echo ""

  proxy:logs:
    desc: 'Follow proxy service logs'
    cmds:
      - docker compose -f {{.TRAEFIK_COMPOSE}} logs -f verdaccio baget registry-dockerhub registry-mcr registry-ghcr {{.CLI_ARGS}}

  proxy:usage:
    desc: 'Show cache disk usage'
    cmds:
      - |
        echo ""
        echo "  Proxy Cache Disk Usage:"
        echo "  ──────────────────────────────────────────"
        for vol in fh-proxy-verdaccio fh-proxy-baget fh-proxy-registry-dockerhub fh-proxy-registry-mcr fh-proxy-registry-ghcr; do
          size=$(docker run --rm -v "${vol}:/data" alpine sh -c "du -sh /data 2>/dev/null | cut -f1" 2>/dev/null || echo "N/A")
          printf "  %-35s %s\n" "$vol" "$size"
        done
        echo ""

  proxy:clean:
    desc: 'Stop proxies and remove cache volumes (with confirmation)'
    prompt: This will remove all cached packages (npm, NuGet, Docker images). Continue?
    cmds:
      - docker compose -f {{.TRAEFIK_COMPOSE}} stop verdaccio baget registry-dockerhub registry-mcr registry-ghcr
      - docker volume rm fh-proxy-verdaccio fh-proxy-baget fh-proxy-registry-dockerhub fh-proxy-registry-mcr fh-proxy-registry-ghcr 2>/dev/null || true
      - echo "Proxy caches removed. Run 'task traefik:up' to recreate."

  hub:
    desc: 'Open Environment Hub in browser'
    cmds:
      - xdg-open https://hub.localhost:4443 2>/dev/null || open https://hub.localhost:4443 2>/dev/null || echo "Open https://hub.localhost:4443 in your browser"
