name: Blank Issue
description: Create a blank issue for custom use cases
title: ""
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Blank Issue
        Use this template when none of the other templates fit your needs.

        Consider using one of the structured templates if possible for better organization.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
    validations:
      required: true
