using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FamilyHub.SourceGenerators;

/// <summary>
/// Roslyn incremental source generator that discovers all IModule implementations
/// and generates a RegisterAllModules() extension method with explicit ordering
/// via [ModuleOrder(N)] attributes.
/// </summary>
[Generator]
public sealed class ModuleRegistrationGenerator : IIncrementalGenerator
{
    private const string IModuleFullName = "FamilyHub.Api.Common.Modules.IModule";
    private const string ModuleOrderFullName = "FamilyHub.Api.Common.Modules.ModuleOrderAttribute";
    private const int DefaultOrder = 1000;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Filter for class declarations that might implement IModule
        var moduleDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsModuleCandidate(node),
                transform: static (ctx, ct) => GetModuleInfo(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        // Step 2: Collect all module infos and generate
        var collected = moduleDeclarations.Collect();

        context.RegisterSourceOutput(collected, static (spc, modules) =>
        {
            if (modules.IsEmpty)
                return;

            var source = GenerateRegistrationSource(modules);
            spc.AddSource("ModuleRegistration.g.cs", source);
        });
    }

    /// <summary>
    /// Quick syntactic filter: class with base list (potential interface implementation).
    /// </summary>
    private static bool IsModuleCandidate(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
            && classDecl.BaseList is not null
            && classDecl.Modifiers.Any(m => m.Text == "sealed");
    }

    /// <summary>
    /// Semantic check: does this class implement IModule? Extract order from [ModuleOrder].
    /// </summary>
    private static ModuleInfo? GetModuleInfo(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol || symbol.IsAbstract)
            return null;

        // Check if it implements IModule
        var implementsIModule = false;
        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.ToDisplayString() == IModuleFullName)
            {
                implementsIModule = true;
                break;
            }
        }

        if (!implementsIModule)
            return null;

        // Extract [ModuleOrder(N)] if present
        var order = DefaultOrder;
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == ModuleOrderFullName
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is int orderValue)
            {
                order = orderValue;
                break;
            }
        }

        return new ModuleInfo(
            symbol.ToDisplayString(),
            symbol.ContainingNamespace.ToDisplayString(),
            order);
    }

    private static string GenerateRegistrationSource(ImmutableArray<ModuleInfo> modules)
    {
        var sorted = modules.OrderBy(m => m.Order).ThenBy(m => m.FullName).ToList();

        // Collect unique namespaces
        var namespaces = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var module in sorted)
        {
            namespaces.Add(module.Namespace);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace FamilyHub.Api.Common.Modules;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated module registration. Discovers all IModule implementations");
        sb.AppendLine($"/// and registers them in [ModuleOrder] order. Found {sorted.Count} module(s).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedModuleRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection RegisterAllModules(");
        sb.AppendLine("        this IServiceCollection services, IConfiguration configuration)");
        sb.AppendLine("    {");

        foreach (var module in sorted)
        {
            var shortName = module.FullName.Substring(module.FullName.LastIndexOf('.') + 1);
            sb.AppendLine($"        services.RegisterModule<{shortName}>(configuration); // order: {module.Order}");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private readonly struct ModuleInfo : IEquatable<ModuleInfo>
    {
        public string FullName { get; }
        public string Namespace { get; }
        public int Order { get; }

        public ModuleInfo(string fullName, string @namespace, int order)
        {
            FullName = fullName;
            Namespace = @namespace;
            Order = order;
        }

        public bool Equals(ModuleInfo other) =>
            FullName == other.FullName && Namespace == other.Namespace && Order == other.Order;

        public override bool Equals(object? obj) => obj is ModuleInfo other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + (FullName?.GetHashCode() ?? 0);
                hash = hash * 31 + (Namespace?.GetHashCode() ?? 0);
                hash = hash * 31 + Order.GetHashCode();
                return hash;
            }
        }
    }
}
