# Docker Swarm Production Stack — Full FamilyHub production environment
# Deploy: IMAGE_TAG=sha-abc1234 docker stack deploy -c docker-stack.production.yml --with-registry-auth fh-production
#
# Requires:
#   - External network: traefik-public (created by base stack)
#   - Swarm secrets: prod_db_password, prod_kc_db_password, prod_kc_admin_password
#   - Node label: node.labels.storage==true (on node hosting stateful services)

version: '3.8'

services:
  # --------------------------------------------------------------------------
  # PostgreSQL — Application database
  # --------------------------------------------------------------------------
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: familyhub
      POSTGRES_USER: familyhub
      POSTGRES_PASSWORD_FILE: /run/secrets/prod_db_password
    volumes:
      - prod-postgres-data:/var/lib/postgresql/data
    networks:
      - prod-internal
    secrets:
      - prod_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == true
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U familyhub -d familyhub']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --------------------------------------------------------------------------
  # PostgreSQL — Keycloak database
  # --------------------------------------------------------------------------
  postgres-keycloak:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/prod_kc_db_password
    volumes:
      - prod-kc-postgres-data:/var/lib/postgresql/data
    networks:
      - prod-internal
    secrets:
      - prod_kc_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == true
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U keycloak -d keycloak']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --------------------------------------------------------------------------
  # Keycloak — OAuth 2.0 / OIDC provider
  # --------------------------------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    command: ['start', '--optimized']
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${PROD_KC_DB_PASSWORD}
      KC_PROXY: edge
      KC_HOSTNAME: auth.familyhub.local
      KC_HOSTNAME_STRICT: 'true'
      KC_HTTP_ENABLED: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${PROD_KC_ADMIN_PASSWORD}
    networks:
      - prod-internal
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == true
      restart_policy:
        condition: any
        delay: 10s
      update_config:
        parallelism: 1
        order: stop-first
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.http.routers.kc-prod.rule=Host(`auth.familyhub.local`)'
        - 'traefik.http.routers.kc-prod.entrypoints=web'
        - 'traefik.http.services.kc-prod.loadbalancer.server.port=8080'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # --------------------------------------------------------------------------
  # API — .NET 10 backend
  # --------------------------------------------------------------------------
  api:
    image: ghcr.io/andrekirst/family2/api:${IMAGE_TAG:-latest}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5152
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=familyhub;Username=familyhub;Password=${PROD_DB_PASSWORD}
      Keycloak__Authority: http://keycloak:8080/realms/FamilyHub-production
      Keycloak__Audience: account
      Keycloak__Issuers: http://keycloak:8080/realms/FamilyHub-production,http://auth.familyhub.local/realms/FamilyHub-production
      Keycloak__ClientId: familyhub-api
      Keycloak__ClientSecret: ${PROD_KC_API_SECRET:-familyhub-api-secret-change-in-production}
      CORS__Origins: http://app.familyhub.local
      Email__Host: ${PROD_SMTP_HOST:-localhost}
      Email__Port: ${PROD_SMTP_PORT:-587}
      Email__Username: ${PROD_SMTP_USERNAME:-}
      Email__Password: ${PROD_SMTP_PASSWORD:-}
      Email__UseSsl: ${PROD_SMTP_SSL:-true}
      Email__FromAddress: noreply@familyhub.local
      App__FrontendUrl: http://app.familyhub.local
      FrontendConfig__ApiUrl: http://app.familyhub.local/graphql
      FrontendConfig__KeycloakIssuer: http://auth.familyhub.local/realms/FamilyHub-production
      FrontendConfig__KeycloakClientId: familyhub-web
      FrontendConfig__AppUrl: http://app.familyhub.local
    networks:
      - prod-internal
      - traefik-public
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        # Direct API access
        - 'traefik.http.routers.api-prod.rule=Host(`api.familyhub.local`)'
        - 'traefik.http.routers.api-prod.entrypoints=web'
        - 'traefik.http.services.api-prod.loadbalancer.server.port=5152'
        # Same-origin proxy: API paths on frontend domain
        - 'traefik.http.routers.api-prod-proxy.rule=Host(`app.familyhub.local`) && (PathPrefix(`/graphql`) || PathPrefix(`/health`) || PathPrefix(`/config`) || PathPrefix(`/api`))'
        - 'traefik.http.routers.api-prod-proxy.entrypoints=web'
        - 'traefik.http.routers.api-prod-proxy.service=api-prod'
        - 'traefik.http.routers.api-prod-proxy.priority=200'
    healthcheck:
      test: ['CMD-SHELL', 'curl -sf http://localhost:5152/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # --------------------------------------------------------------------------
  # Frontend — Angular SPA via nginx
  # --------------------------------------------------------------------------
  frontend:
    image: ghcr.io/andrekirst/family2/frontend:${IMAGE_TAG:-latest}
    networks:
      - traefik-public
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.http.routers.frontend-prod.rule=Host(`app.familyhub.local`)'
        - 'traefik.http.routers.frontend-prod.entrypoints=web'
        - 'traefik.http.routers.frontend-prod.priority=100'
        - 'traefik.http.services.frontend-prod.loadbalancer.server.port=80'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost/nginx-health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  prod-postgres-data:
  prod-kc-postgres-data:

secrets:
  prod_db_password:
    external: true
  prod_kc_db_password:
    external: true
  prod_kc_admin_password:
    external: true

networks:
  prod-internal:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
