# Docker Swarm Base Stack — Shared Infrastructure
# Deploy once: docker stack deploy -c docker-stack.base.yml fh-base
#
# Provides Traefik reverse proxy shared by staging + production stacks.

version: '3.8'

services:
  traefik:
    image: traefik:v3.2
    command:
      - '--configFile=/etc/traefik/traefik-swarm.yml'
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik-swarm.yml
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.dashboard.rule=Host(`traefik.familyhub.local`)'
        - 'traefik.http.routers.dashboard.service=api@internal'
        - 'traefik.http.routers.dashboard.entrypoints=web'
        - 'traefik.http.services.dashboard.loadbalancer.server.port=8080'
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

configs:
  traefik-config:
    file: ./traefik/traefik-swarm.yml

networks:
  traefik-public:
    driver: overlay
    attachable: true
    external: true
