/**
 * Optimistic update utilities for Apollo Client mutations.
 *
 * These helpers standardize the creation of optimistic responses,
 * which allow the UI to update immediately before the server confirms
 * a mutation. Apollo replaces the optimistic data with the real server
 * response once it arrives, or rolls back on error.
 */

import { ApolloCache } from '@apollo/client/core';

/**
 * Prefix used to distinguish client-generated optimistic IDs
 * from server-generated IDs.
 */
const OPTIMISTIC_ID_PREFIX = 'optimistic-';

/**
 * Generate a temporary client-side ID for optimistic responses.
 *
 * The ID is prefixed with "optimistic-" so consumers can detect
 * whether an entity is still pending server confirmation.
 *
 * @returns A unique string ID prefixed with "optimistic-"
 */
export function createOptimisticId(): string {
  return `${OPTIMISTIC_ID_PREFIX}${crypto.randomUUID()}`;
}

/**
 * Check whether a given ID was generated by `createOptimisticId()`.
 *
 * Useful for showing pending/loading indicators on entities that
 * have not yet been confirmed by the server.
 *
 * @param id - The entity ID to check
 * @returns True if the ID was generated client-side
 */
export function isOptimisticId(id: string): boolean {
  return id.startsWith(OPTIMISTIC_ID_PREFIX);
}

/**
 * Create an optimistic response object with the required `__typename`
 * field that Apollo uses for cache normalization.
 *
 * @typeParam T - The GraphQL type shape being optimistically created
 * @param typename - The GraphQL `__typename` value (e.g. "Family", "CalendarEvent")
 * @param data - Partial data to include in the optimistic response
 * @returns A complete object with `__typename` set, suitable for Apollo's `optimisticResponse`
 *
 * @example
 * ```ts
 * const optimistic = createOptimisticResponse<Family>('Family', {
 *   id: createOptimisticId(),
 *   name: 'Smith Family',
 * });
 * ```
 */
export function createOptimisticResponse<T extends Record<string, unknown>>(
  typename: string,
  data: Partial<T>,
): T & { __typename: string } {
  return {
    __typename: typename,
    ...data,
  } as T & { __typename: string };
}

/**
 * Configuration shape for an optimistic mutation update.
 *
 * Consumers define one of these per mutation to describe:
 * - how to build the optimistic response
 * - how to update the Apollo cache
 *
 * @typeParam TData - The mutation result type
 * @typeParam TVars - The mutation variables type
 */
export interface OptimisticConfig<TData, TVars = Record<string, unknown>> {
  /** Build the optimistic response from the mutation variables. */
  getOptimisticResponse: (variables: TVars) => TData;

  /**
   * Optional cache update function.
   * Called with the Apollo cache proxy and the mutation result (or optimistic data).
   * Use this to insert/remove/reorder items in cached queries.
   */
  updateCache?: (cache: ApolloCache, data: TData) => void;
}
