# Family Member Invites Feature Specification
# Retrofit spec for completed feature (#97) - validates spec-driven workflow

apiVersion: agent-os/v1
kind: FeatureSpec
metadata:
  name: 'family-member-invites'
  module: 'family'
  issue: '#97'
  phase: 'phase-0'
  status: completed

spec:
  description: |
    Enable family owners and admins to invite new members via email.
    Supports both single invitations and batch invitations (max 20).
    Implements "Accept First" flow for unauthenticated users and
    immediate acceptance for authenticated users.

  acceptance:
    - 'Family owner/admin can invite members by email'
    - 'Batch invitations with partial success handling'
    - 'Email sent with invitation link and display code'
    - 'Unauthenticated users can preview invitation before signing up'
    - 'Authenticated users can accept invitation immediately'
    - 'Duplicate and invalid invitations return specific error codes'
    - 'Invitations expire after 14 days'

  domain:
    aggregates:
      - name: 'FamilyMemberInvitation'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Domain/Aggregates/FamilyMemberInvitation.cs'
        properties:
          - name: Id
            type: 'InvitationId'
            required: true
          - name: FamilyId
            type: 'FamilyId'
            required: true
          - name: Email
            type: 'Email'
            required: true
          - name: Role
            type: 'FamilyRole'
            required: true
          - name: Token
            type: 'InvitationToken'
            required: true
          - name: DisplayCode
            type: 'InvitationDisplayCode'
            required: true
          - name: ExpiresAt
            type: 'DateTime'
            required: true
          - name: InvitedByUserId
            type: 'UserId'
            required: true
          - name: Status
            type: 'InvitationStatus'
            required: true
          - name: Message
            type: 'string'
            required: false

    valueObjects:
      - name: 'InvitationId'
        baseType: 'Guid'
        validation: 'Non-empty GUID'
      - name: 'InvitationToken'
        baseType: 'string'
        validation: 'Secure random 32-byte token'
      - name: 'InvitationDisplayCode'
        baseType: 'string'
        validation: 'Format: ABC-DEF-123 (3-3-3)'
      - name: 'InvitationStatus'
        baseType: 'string'
        validation: 'Enum: Pending, Accepted, Expired, Canceled'

    events:
      - name: 'FamilyMemberInvitedEvent'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Domain/Events/FamilyMemberInvitedEvent.cs'
        triggers: 'Invitation created or resent'
        payload:
          - InvitationId
          - FamilyId
          - Email
          - Role
          - Token
          - ExpiresAt
          - InvitedByUserId
          - Message
          - IsResend
        handlers:
          - 'FamilyMemberInvitedEventHandler (sends email)'

      - name: 'InvitationAcceptedEvent'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Domain/Events/InvitationAcceptedEvent.cs'
        triggers: 'User accepts invitation'
        handlers:
          - 'Adds user to family roster'

      - name: 'InvitationCanceledEvent'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Domain/Events/InvitationCanceledEvent.cs'
        triggers: 'Owner/admin cancels invitation'
        handlers: []

  api:
    mutations:
      - name: 'InviteFamilyMemberByEmail'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Presentation/GraphQL/Mutations/InvitationMutations.cs'
        input:
          - field: familyId
            type: 'Guid'
            required: true
          - field: email
            type: 'string'
            required: true
          - field: role
            type: 'string'
            required: true
          - field: message
            type: 'string'
            required: false
        returns: 'InviteFamilyMemberByEmailResult'
        command: 'InviteFamilyMemberByEmailCommand'
        authorization: 'IRequireOwnerOrAdminRole'

      - name: 'InviteFamilyMembers'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Presentation/GraphQL/Mutations/InvitationMutations.cs'
        input:
          - field: familyId
            type: 'Guid'
            required: true
          - field: invitations
            type: 'InvitationRequestInput[]'
            required: true
          - field: message
            type: 'string'
            required: false
        returns: 'InviteFamilyMembersDto'
        command: 'InviteFamilyMembersCommand'
        authorization: 'IRequireOwnerOrAdminRole'
        notes: 'Supports partial success - valid invitations proceed, invalid return error codes'

    queries:
      - name: 'GetInvitationByToken'
        parameters:
          - token
        returns: 'InvitationPreview'

      - name: 'GetPendingInvitations'
        parameters:
          - familyId
        returns: 'FamilyMemberInvitation[]'

  ui:
    pages:
      - route: '/family/create'
        component: 'FamilyCreationWizardPage'
        notes: 'Wizard includes invite-members-step as step 2'

      - route: '/invitation/accept/:token'
        component: 'InvitationAcceptPage'
        notes: 'Preview and accept invitation flow'

    components:
      - name: 'invite-members-step'
        type: 'organism'
        location: 'src/frontend/family-hub-web/src/app/features/family/components/invite-members-step/'
        features:
          - 'FormArray for dynamic email inputs (max 20)'
          - 'Per-email role selection'
          - 'Client-side duplicate detection'
          - 'Optional personal message (max 500 chars)'
          - 'Skip functionality (step optional)'

      - name: 'invite-member-modal'
        type: 'organism'
        location: 'src/frontend/family-hub-web/src/app/features/family/components/invite-member-modal/'
        features:
          - 'Post-creation invitation modal'
          - 'Batch invitations with results display'
          - 'Auto-close on success'

  testing:
    unit:
      - target: 'InviteFamilyMembersCommandHandler'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Application/Commands/InviteFamilyMembers/'
        scenarios:
          - 'happy-path: valid batch creates invitations'
          - 'validation: duplicate emails in batch rejected'
          - 'validation: self-invite rejected'
          - 'validation: existing member rejected'
          - 'partial-success: mix of valid and invalid processed correctly'

      - target: 'FamilyMemberInvitation'
        location: 'src/api/Modules/FamilyHub.Modules.Family/Domain/Aggregates/'
        scenarios:
          - 'Create: emits FamilyMemberInvitedEvent'
          - 'Accept: changes status, emits InvitationAcceptedEvent'
          - 'Cancel: changes status, emits InvitationCanceledEvent'
          - 'Resend: generates new token, emits event with IsResend=true'

    integration:
      - target: 'InvitationRepository'
        scenarios:
          - 'persistence: invitation saved to database'
          - 'retrieval: invitation retrieved by token'
          - 'rls: only family invitations visible'

    e2e:
      - flow: 'email-verification'
        location: 'src/frontend/family-hub-web/e2e/tests/invitation-email-verification.spec.ts'
        steps:
          - 'Create family via API'
          - 'Invite member via API'
          - 'Verify email in MailHog'
          - 'Check recipient, subject, body content'
          - 'Verify invitation link and display code'

      - flow: 'invitation-acceptance'
        location: 'src/frontend/family-hub-web/e2e/tests/invitation-acceptance.spec.ts'
        steps:
          - 'Create invitation'
          - 'Navigate to acceptance page'
          - 'Preview invitation details'
          - 'Accept invitation'
          - 'Verify redirect and events'

      - flow: 'wizard-integration'
        location: 'src/frontend/family-hub-web/e2e/tests/family-creation-wizard.spec.ts'
        steps:
          - 'Navigate wizard to invite step'
          - 'Add email invitations'
          - 'Complete wizard'
          - 'Verify invitations sent'

  dependencies:
    blocking: []
    optional:
      - 'Email service (SMTP/MailHog)'

  eventChains:
    triggers:
      - 'FamilyMemberInvitedEvent'
      - 'InvitationAcceptedEvent'
      - 'InvitationCanceledEvent'
    handlers:
      - 'Email sending on FamilyMemberInvitedEvent'
      - 'Family roster update on InvitationAcceptedEvent'

  security:
    rls: true
    roles:
      - 'OWNER'
      - 'ADMIN'
    notes: 'Only family owners and admins can invite members'

  errorHandling:
    codes:
      - code: 'ALREADY_MEMBER'
        description: 'Email is already a family member'
      - code: 'DUPLICATE_PENDING_INVITATION'
        description: 'Email already has pending invitation'
      - code: 'MEMBER_OF_ANOTHER_FAMILY'
        description: 'Cross-family membership check'
      - code: 'SELF_INVITE'
        description: 'Cannot invite yourself'
      - code: 'INVALID_ROLE'
        description: 'Cannot invite as OWNER'
      - code: 'DUPLICATE_IN_BATCH'
        description: 'Duplicate email in same batch request'
      - code: 'INVALID_EMAIL'
        description: 'Email format invalid'

progress:
  percentage: 100
  lastUpdated: '2026-01-25'
  completedItems:
    - 'Domain aggregate and value objects'
    - 'Domain events'
    - 'GraphQL mutations'
    - 'Command handlers with partial success'
    - 'Frontend wizard step component'
    - 'Frontend invitation modal'
    - 'E2E tests for email verification'
    - 'E2E tests for invitation acceptance'
    - 'E2E tests for wizard integration'
